# Example Pipeline YAML
# This demonstrates the edge format compatible with pipeline_factory.py

pipeline:
  name: Document Processing Pipeline
  description: Extract, analyze, and index documents with parallel processing
  
  executors:
    # Input
    - id: retrieve-docs
      name: Retrieve Documents
      type: blob-input
      description: Retrieve PDF documents from blob storage
      position:
        x: 100
        y: 200
      settings:
        containerName: documents
        pathPattern: "*.pdf"
    
    # Parallel processing paths
    - id: extract-text
      name: Extract Text
      type: pdf-extractor
      description: Extract raw text content from PDF
      position:
        x: 300
        y: 100
      settings:
        extractImages: false
    
    - id: extract-structure
      name: Extract Structure
      type: document-intelligence-extractor
      description: Extract document layout and structure
      position:
        x: 300
        y: 200
      settings:
        modelId: prebuilt-layout
    
    - id: analyze-content
      name: Analyze Content
      type: custom-ai-prompt
      description: AI-powered content analysis and insights
      position:
        x: 300
        y: 300
      settings:
        systemPrompt: "Analyze the document content and extract key insights"
    
    # Combine results
    - id: combine-results
      name: Combine Results
      type: result-combiner
      description: Merge results from all processing paths
      position:
        x: 500
        y: 200
      settings:
        combineStrategy: merge_fields
        waitForAll: true
    
    # Output
    - id: index-output
      name: Index to Search
      type: ai-search-index-output
      description: Index combined results to Azure AI Search
      position:
        x: 700
        y: 200
      settings:
        indexName: documents
  
  edges:
    # Fan-out: One source to multiple parallel paths
    - from: retrieve-docs
      to: [extract-text, extract-structure, analyze-content]
      type: parallel
      description: "Process document through 3 parallel extraction paths"
    
    # Fan-in: Multiple sources join at combiner
    - from: [extract-text, extract-structure, analyze-content]
      to: combine-results
      type: join
      wait_strategy: all
      description: "Wait for all extraction paths to complete"
    
    # Sequential: Simple one-to-one connection
    - from: combine-results
      to: index-output
      type: sequential
      description: "Index the combined results"
